import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { JSDOM } from "jsdom";
import { History } from "../server/history.js";

const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
const archive = await History.load();
const catalog = archive.seasons("2026");
const flush = async () => { await new Promise(setImmediate); await new Promise(setImmediate); };

function environment(t, url = "http://localhost/") {
  const dom = new JSDOM(html, { url });
  for (const key of ["window", "document", "Node", "location", "history"]) {
    const old = Object.getOwnPropertyDescriptor(globalThis, key);
    Object.defineProperty(globalThis, key, { value: dom.window[key], configurable: true, writable: true });
    t.after(() => { if (old) Object.defineProperty(globalThis, key, old); else delete globalThis[key]; });
  }
  dom.window.HTMLElement.prototype.scrollIntoView = function () {};
  t.after(() => dom.window.close());
  return dom.window.document;
}

test("season UI: archive recap, owner profiles, links, visible-tab keyboard navigation and preferences", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?test=${Date.now()}`);
  const selections = [];
  ui.initializeUi({ onRefresh() {}, onSeasonChange: (...args) => selections.push(args) });
  ui.renderSeasons(catalog, "2025");
  doc.getElementById("liveTab").click();
  ui.prepareSeason("2025", true, null);
  const payload = archive.dashboard("2025");
  ui.renderDashboard(payload.stats, payload);
  assert.equal(doc.getElementById("overviewTab").getAttribute("aria-selected"), "true");
  assert.equal(doc.getElementById("liveTab").hidden, true);
  assert.equal(doc.getElementById("draftTab").hidden, true);
  assert.equal(doc.getElementById("refreshButton").hidden, true);
  assert.equal(doc.getElementById("statusTitle").textContent, "ESPN archive");
  assert.match(doc.getElementById("seasonRange").textContent, /14.*10 teams/);
  assert.equal(doc.querySelectorAll("#matrixTable tbody tr").length, 10);
  assert.match(doc.getElementById("seasonRecap").textContent, /Champion/);
  doc.getElementById("overviewTab").dispatchEvent(new window.KeyboardEvent("keydown", { key: "ArrowRight", bubbles: true }));
  assert.equal(doc.activeElement.id, "weeklyTab");
  doc.getElementById("weeklyTab").dispatchEvent(new window.KeyboardEvent("keydown", { key: "End", bubbles: true }));
  assert.equal(doc.activeElement.id, "ownersTab");
  const mode = [...doc.querySelectorAll("#matrixControls button")].find((button) => button.textContent.includes("Rank"));
  mode.click();
  assert.equal(doc.querySelectorAll("#trendControls input").length, 0);
  assert.equal(doc.querySelectorAll("#trendChart .chart-line").length, 10);
  const originalLine = doc.querySelector('#trendChart [data-owner="gaurav"]');
  const originalStyle = [originalLine.getAttribute("stroke"), originalLine.getAttribute("stroke-dasharray")];
  const past = archive.dashboard("2018");
  ui.prepareSeason("2018", true, "gaurav");
  ui.renderDashboard(past.stats, past);
  assert.match(doc.getElementById("seasonRange").textContent, /13.*12 teams/);
  assert.equal(doc.querySelectorAll("#matrixTable tbody tr").length, 12);
  assert.match(doc.querySelector("#matrixTable .owner-highlight").textContent, /Gaurav/);
  assert.match(doc.querySelector("#matrixTable caption").textContent, /rank/);
  assert.equal(doc.querySelectorAll("#trendChart .chart-line").length, 12);
  assert.equal(doc.querySelectorAll("#trendControls .trend-owner-key").length, 12);
  const oldLine = doc.querySelector('#trendChart [data-owner="gaurav"]');
  assert.deepEqual([oldLine.getAttribute("stroke"), oldLine.getAttribute("stroke-dasharray")], originalStyle);
  ui.renderOwners(archive.careers(null, { currentSeason: "2026" }));
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 14);
  assert.equal([...doc.querySelectorAll("#ownersContent thead th")].some((cell) => cell.textContent.includes("Titles")), false);
  const filter = doc.getElementById("currentOwnersOnly");
  filter.checked = true;
  filter.dispatchEvent(new window.Event("change"));
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 10);
  const gaurav = [...doc.querySelectorAll(".owner-button")].find((button) => button.textContent.includes("Gaurav"));
  assert.match(gaurav.textContent, /🏆/);
  gaurav.click();
  assert.match(doc.querySelector("#ownersContent h3").textContent, /^Gaurav Gandhi/);
  assert.match(doc.querySelector("#ownersContent h3").textContent, /🏆/);
  const link = doc.querySelector("#ownersContent a");
  assert.match(link.href, /season=2025&owner=gaurav/);
  link.click();
  assert.deepEqual(selections.at(-1), ["2025", "gaurav"]);
  ui.prepareSeason("2026", false, null);
  assert.equal(doc.getElementById("draftTab").hidden, false);
  assert.equal(doc.getElementById("refreshButton").hidden, false);
});

test("client ignores late season/refresh responses and handles deep links and back navigation", async (t) => {
  const doc = environment(t);
  let resolveOldSeason;
  let resolveRefresh;
  const oldFetch = globalThis.fetch;
  t.after(() => { globalThis.fetch = oldFetch; });
  const current = archive.dashboard("2025");
  current.source = "sleeper";
  current.stats.metadata.season = "2026";
  current.recap = null;
  const response = (body) => ({ ok: true, json: async () => body });
  globalThis.fetch = async (url) => {
    if (url === "/api/seasons") return response(catalog);
    if (url === "/api/owners") return response(archive.careers(null, { currentSeason: "2026" }));
    if (url === "/api/refresh") return new Promise((resolve) => { resolveRefresh = () => resolve(response(current)); });
    if (url.endsWith("season=2018")) return new Promise((resolve) => { resolveOldSeason = () => resolve(response(archive.dashboard("2018"))); });
    if (url.endsWith("season=2025")) return response(archive.dashboard("2025"));
    return response(current);
  };
  const source = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replace('"./ui.js"', JSON.stringify(`${new URL("../src/ui.js", import.meta.url).href}?race=${Date.now()}`));
  await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
  assert.match(doc.getElementById("brandSeason").textContent, /2026/);
  const select = doc.getElementById("seasonSelect");
  select.value = "2018";
  select.dispatchEvent(new window.Event("change"));
  select.value = "2025";
  select.dispatchEvent(new window.Event("change"));
  await flush();
  assert.match(doc.getElementById("brandSeason").textContent, /2025/);
  resolveOldSeason(); resolveRefresh(); await flush();
  assert.match(doc.getElementById("brandSeason").textContent, /2025/);
  assert.equal(doc.querySelectorAll("#matrixTable tbody tr").length, 10);
  assert.equal(doc.getElementById("refreshButton").hidden, true);
  history.pushState(null, "", "?season=2018&owner=gaurav");
  window.dispatchEvent(new window.PopStateEvent("popstate"));
  resolveOldSeason(); await flush();
  assert.match(doc.getElementById("brandSeason").textContent, /2018/);
  assert.match(doc.querySelector(".owner-highlight").textContent, /Gaurav/);
  assert.equal(doc.getElementById("seasonSelect").value, "2018");
});

test("initial archive deep link loads highlighted owner without refreshing Sleeper", async (t) => {
  const doc = environment(t, "http://localhost/?season=2022&owner=gaurav");
  const oldFetch = globalThis.fetch;
  t.after(() => { globalThis.fetch = oldFetch; });
  const calls = [];
  globalThis.fetch = async (url) => {
    calls.push(url);
    const payload = url === "/api/seasons" ? catalog : url === "/api/owners" ? archive.careers(null, { currentSeason: "2026" }) : archive.dashboard("2022");
    return { ok: true, json: async () => payload };
  };
  const source = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replace('"./ui.js"', JSON.stringify(`${new URL("../src/ui.js", import.meta.url).href}?deep=${Date.now()}`));
  await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
  await flush();
  assert.equal(calls.includes("/api/refresh"), false);
  assert.equal(doc.getElementById("seasonSelect").value, "2022");
  assert.match(doc.querySelector(".owner-highlight").textContent, /Gaurav/);
  assert.doesNotMatch(doc.getElementById("seasonRecap").textContent, /Manual True League title correction/);
  assert.match(doc.getElementById("seasonRecap").textContent, /Champion · Gaurav Gandhi/);
  assert.match(doc.getElementById("ownersStatus").textContent, /Current-season contributions are unavailable/);
});

test("trend sums weekly score-minus-median with full precision and excludes provisional weeks", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?cumulative=${Date.now()}`);
  ui.initializeUi({ onRefresh() {} });
  const payload = archive.dashboard("2025");
  payload.stats.weeks = payload.stats.weeks.slice(0, 2);
  const team = payload.stats.teams[0];
  payload.stats.weeks[0].entries.find((entry) => entry.rosterId === team.rosterId).score = 12.34;
  payload.stats.weeks[1].entries.find((entry) => entry.rosterId === team.rosterId).score = 23.45;
  payload.stats.weeks[0].leagueMedian = 10;
  payload.stats.weeks[1].leagueMedian = 30;
  payload.stats.liveWeek = { ...structuredClone(payload.stats.weeks[1]), week: 3, status: "live" };
  ui.renderDashboard(payload.stats, payload);
  const titles = [...doc.querySelectorAll("#trendChart .chart-dot title")].map((node) => node.textContent);
  assert.ok(titles.includes(`${team.managerName}, through Week 1: +2.34 cumulative vs median`));
  assert.ok(titles.includes(`${team.managerName}, through Week 2: -4.21 cumulative vs median`));
  assert.ok(titles.every((title) => !title.includes("Week 3")));
  assert.ok(doc.querySelector("#trendChart .chart-median"));
  payload.stats.weeks = payload.stats.weeks.slice(0, 1);
  ui.renderDashboard(payload.stats, payload);
  assert.ok(!doc.querySelector("#trendChart svg").outerHTML.includes("NaN"));
  payload.stats.weeks = [];
  ui.renderDashboard(payload.stats, payload);
  assert.match(doc.getElementById("trendChart").textContent, /No finalized trends yet/);
});

test("live matrix cells have no heat or median marker and do not rescale finalized cells", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?matrix=${Date.now()}`);
  ui.initializeUi({ onRefresh() {} });
  const payload = archive.dashboard("2025");
  payload.stats.weeks = payload.stats.weeks.slice(0, 1);
  ui.renderDashboard(payload.stats, payload);
  const shades = [...doc.querySelectorAll("#matrixTable .matrix-scored")].map((cell) => cell.getAttribute("style"));
  const totals = [...doc.querySelectorAll("#matrixTable tbody tr")].map((row) => row.lastElementChild.textContent);
  assert.equal(doc.querySelector("#matrixTable thead tr").lastElementChild.textContent, "Total PF");
  assert.deepEqual(totals, payload.stats.teams.map((team) => team.total.toFixed(2)));
  payload.stats.liveWeek = { ...structuredClone(payload.stats.weeks[0]), week: 2, status: "live" };
  payload.stats.liveWeek.entries.forEach((entry) => { entry.score = 99999; });
  ui.renderDashboard(payload.stats, payload);
  assert.deepEqual([...doc.querySelectorAll("#matrixTable .matrix-scored")].map((cell) => cell.getAttribute("style")), shades);
  assert.equal(doc.querySelectorAll("#matrixTable .matrix-live-cell.matrix-scored, #matrixTable .matrix-live-cell .matrix-median-marker").length, 0);
  assert.match(doc.querySelector(".matrix-live-head").textContent, /Live/);
  assert.ok(doc.querySelectorAll("#statbookTable .career-colored").length > 0);
  assert.equal(doc.querySelector("#statbookTable tbody tr").firstElementChild.classList.contains("career-colored"), false);
  assert.equal(doc.querySelector("#statbookTable .record-pill").parentElement.classList.contains("career-colored"), false);
  assert.equal(doc.getElementById("statbookTable").compareDocumentPosition(doc.getElementById("leagueBenchmarks")) & Node.DOCUMENT_POSITION_FOLLOWING, Node.DOCUMENT_POSITION_FOLLOWING);
  assert.doesNotMatch(doc.getElementById("leagueBenchmarks").textContent, /Median pts > median|Finalized scores/);
  assert.match(doc.getElementById("leagueBenchmarks").textContent, /Season high/);
  assert.match(doc.getElementById("leagueBenchmarks").textContent, /Season low/);
  for (const button of doc.querySelectorAll("#matrixControls button")) {
    button.click();
    assert.deepEqual([...doc.querySelectorAll("#matrixTable tbody tr")].map((row) => row.lastElementChild.textContent), totals);
    const count = doc.querySelector("#matrixTable thead tr").children.length;
    assert.ok([...doc.querySelectorAll("#matrixTable tbody tr, #matrixTable tfoot tr")].every((row) => row.children.length === count));
  }
  assert.doesNotMatch(doc.body.textContent, /Red to green =|Regular-season results across all seasons/);
});

test("owner sorting, era profiles, conditional colors and matching-cache fallback", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?owners=${Date.now()}`);
  ui.initializeUi({ onRefresh() {} });
  const all = archive.careers(null);
  const ten = archive.careers(null, { era: "ten-team" });
  ui.renderOwners(all);
  const header = (label) => [...doc.querySelectorAll("#ownersContent thead button")].find((button) => button.textContent.replace(/[↑↓]/g, "").trim() === label);
  header("PF").click();
  assert.match(doc.querySelector("#ownersContent .owner-button").textContent, new RegExp([...all.owners].sort((a, b) => b.pointsFor - a.pointsFor)[0].name));
  assert.equal(doc.activeElement, header("PF"));
  assert.equal(doc.querySelectorAll('#ownersContent th[aria-sort="descending"]').length, 1);
  assert.equal(doc.querySelector("#ownersContent tbody th").classList.contains("career-colored"), false);
  assert.ok(doc.querySelectorAll("#ownersContent .career-colored").length > 0);
  const kyle = [...doc.querySelectorAll(".owner-button")].find((button) => button.textContent.includes("Kyle"));
  kyle.click();
  ui.prepareOwnerEra("ten-team");
  assert.doesNotMatch(doc.getElementById("ownersContent").textContent, /Kyle/);
  ui.renderOwners(ten);
  assert.match(doc.getElementById("ownersContent").textContent, /No seasons in this era/);
  ui.prepareOwnerEra("all");
  ui.renderOwners(all);
  assert.match(doc.querySelector("#ownersContent h3").textContent, /Kyle/);
  assert.ok(doc.querySelector(".career-performance"));
  header("Season").click();
  const seasonLink = () => doc.querySelector("#ownersContent a").textContent;
  assert.equal(seasonLink(), "2018");
  ui.renderOwners(all);
  assert.equal(seasonLink(), "2018");
  doc.getElementById("currentOwnersOnly").checked = true;
  doc.getElementById("currentOwnersOnly").dispatchEvent(new window.Event("change"));
  assert.match(doc.querySelector("#ownersContent h3").textContent, /Kyle/);
  ui.prepareOwnerEra("ten-team");
  ui.renderOwners(null);
  assert.match(doc.getElementById("ownersStatus").textContent, /previous data for this era retained/);
  assert.match(doc.getElementById("ownersContent").textContent, /No seasons in this era/);
  doc.querySelector("#ownersContent .refresh-button").click();
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 10);
  assert.ok([...doc.querySelectorAll("#ownersContent tbody tr")].every((row) => !row.textContent.includes("Kyle")));
  const neutral = structuredClone(ten);
  neutral.owners.forEach((owner) => { owner.pointsFor = 100; owner.winPct = 0.5; owner.averageDeltaMedian = 0; });
  ui.renderOwners(neutral);
  const first = doc.querySelector("#ownersContent tbody tr");
  for (const index of [3, 4, 7]) assert.equal(first.children[index].style.getPropertyValue("--score-shade"), "0.00%");
});

test("era switching ignores late responses and never presents all-era totals as ten-team", async (t) => {
  const doc = environment(t, "http://localhost/?season=2025");
  const oldFetch = globalThis.fetch;
  t.after(() => { globalThis.fetch = oldFetch; });
  let resolveTen;
  let failTen = false;
  const response = (body) => ({ ok: true, json: async () => body });
  globalThis.fetch = async (url) => {
    if (url === "/api/seasons") return response(catalog);
    if (url === "/api/owners") return response(archive.careers(null));
    if (url === "/api/owners?era=ten-team") {
      if (failTen) throw new Error("offline");
      return new Promise((resolve) => { resolveTen = () => resolve(response(archive.careers(null, { era: "ten-team" }))); });
    }
    return response(archive.dashboard("2025"));
  };
  const source = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replace('"./ui.js"', JSON.stringify(`${new URL("../src/ui.js", import.meta.url).href}?eraRace=${Date.now()}`));
  await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
  await flush();
  const change = (value) => { doc.getElementById("ownerEra").value = value; doc.getElementById("ownerEra").dispatchEvent(new window.Event("change")); };
  change("ten-team");
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 0);
  change("all"); await flush();
  resolveTen(); await flush();
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 14);
  assert.equal(doc.getElementById("ownerEra").value, "all");
  failTen = true;
  change("ten-team"); await flush();
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 0);
  assert.match(doc.getElementById("ownersContent").textContent, /unavailable/);
});
