import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { JSDOM } from "jsdom";
import { History } from "../server/history.js";
import { leagueRecords, headToHead } from "../server/records.js";

const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
const archive = await History.load();
const catalog = archive.seasons("2026");
const flush = async () => { await new Promise(setImmediate); await new Promise(setImmediate); };

test("record and rivalry panels render archive results, empty selectors, sorting and accessible links", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?research=${Date.now()}`);
  const selections = [];
  ui.initializeUi({ onRefresh() {}, onSeasonChange: (...args) => selections.push(args) });
  assert.deepEqual([...doc.querySelectorAll('[role="tab"]')].map((tab) => tab.textContent), ["Scoreboard", "Live Scores", "Trends", "Stat book", "Draft Board", "Owners", "Records", "Head-to-Head"]);
  doc.getElementById("recordsTab").click();
  doc.getElementById("recordsTab").dispatchEvent(new window.KeyboardEvent("keydown", { key: "ArrowRight", bubbles: true }));
  assert.equal(doc.activeElement.id, "headToHeadTab");
  doc.getElementById("headToHeadTab").dispatchEvent(new window.KeyboardEvent("keydown", { key: "End", bubbles: true }));
  assert.equal(doc.activeElement.id, "headToHeadTab");
  ui.prepareRecords("ten-team");
  const records = leagueRecords(archive.archive, null);
  ui.renderRecords(records);
  assert.equal(doc.querySelectorAll(".record-section").length, 11);
  assert.match(doc.getElementById("recordsStatus").textContent, /Current-season results unavailable/);
  const closestSection = [...doc.querySelectorAll(".record-section")].find((section) => section.querySelector("h3")?.textContent === "Closest matchup");
  assert.equal(closestSection.querySelector(".record-matchup").textContent, `${records.records.closestMatchup[0].home.ownerName}vs${records.records.closestMatchup[0].away.ownerName}`);
  assert.match(closestSection.querySelector(".record-row").textContent, new RegExp(`${records.records.closestMatchup[0].home.teamName}.*${records.records.closestMatchup[0].away.teamName}`));
  const link = doc.querySelector("#recordsContent a");
  const params = new URL(link.href).searchParams;
  link.click();
  assert.deepEqual(selections.at(-1), [params.get("season"), params.get("owner")]);
  ui.prepareRecords("all");
  assert.equal(doc.querySelectorAll(".record-section").length, 0);
  ui.renderRecords(records); // Wrong-era response cannot overwrite the selection.
  assert.equal(doc.querySelectorAll(".record-section").length, 0);
  ui.renderRecords(leagueRecords(archive.archive, null, { era: "all" }));
  assert.match(doc.getElementById("recordsStatus").textContent, /2018/);
  ui.renderRecords(null);
  assert.equal(doc.querySelectorAll(".record-section").length, 11);
  assert.match(doc.getElementById("recordsStatus").textContent, /retained/);
  ui.prepareRivalry({ era: "ten-team", ownerA: "", ownerB: "" });
  ui.renderRivalry(headToHead(archive.archive, null));
  assert.equal(doc.getElementById("h2hOwnerA").value, "");
  assert.equal(doc.getElementById("h2hOwnerB").value, "");
  assert.match(doc.getElementById("headToHeadContent").textContent, /Choose two owners/);
  ui.prepareRivalry({ era: "all", ownerA: "gaurav", ownerB: "alex" });
  const pair = headToHead(archive.archive, null, { era: "all", ownerA: "gaurav", ownerB: "alex" });
  ui.renderRivalry(pair);
  assert.equal(doc.querySelectorAll(".rivalry-table tbody tr").length, pair.matchups.length);
  const firstWinner = doc.querySelector(".rivalry-table tbody tr td:nth-child(6) .owner-icon-label");
  const expectedWinner = pair.matchups[0].winnerId === pair.ownerA.id ? pair.ownerA.name : pair.ownerB.name;
  assert.equal(firstWinner.title, expectedWinner);
  assert.equal(firstWinner.querySelector("img").alt, expectedWinner);
  firstWinner.querySelector("img").dispatchEvent(new window.Event("error"));
  assert.equal(firstWinner.textContent, expectedWinner.split(/\s+/)[0]);
  assert.equal(doc.querySelectorAll("#headToHeadContent .benchmark").length, 0);
  assert.deepEqual([...doc.querySelectorAll(".rivalry-comparison thead th")].map((cell) => cell.querySelector(".rivalry-header-avatar")?.getAttribute("aria-label") || cell.textContent), ["Metric", "Gaurav Gandhi", "Alex Henoch"]);
  assert.deepEqual([...doc.querySelectorAll(".rivalry-comparison .owner-icon")].map((img) => img.getAttribute("src")), ["./img/avatars/gaurav.png", "./img/avatars/alex.png"]);
  const comparisonRows = [...doc.querySelectorAll(".rivalry-comparison tbody tr")];
  const valuesFor = (label) => [...comparisonRows.find((row) => row.firstChild.textContent === label).querySelectorAll("td")];
  assert.deepEqual(valuesFor("Series record").map((cell) => cell.textContent), [`${pair.summary.wins}–${pair.summary.losses}`, `${pair.summary.losses}–${pair.summary.wins}`]);
  assert.deepEqual(valuesFor("Points for").map((cell) => cell.textContent), [pair.summary.pointsFor.toFixed(2), pair.summary.pointsAgainst.toFixed(2)]);
  assert.equal(valuesFor("Points for")[0].style.getPropertyValue("--score-color"), pair.summary.pointsFor > pair.summary.pointsAgainst ? "var(--score-high)" : "var(--score-low)");
  assert.equal(valuesFor("Points against")[0].style.getPropertyValue("--score-color"), valuesFor("Points for")[0].style.getPropertyValue("--score-color"));
  assert.ok(valuesFor("Games").every((cell) => !cell.classList.contains("career-colored")));
  assert.match(doc.getElementById("headToHeadContent").textContent, /Playoffs/);
  const margin = [...doc.querySelectorAll("#headToHeadContent th button")].find((button) => button.textContent.includes("Margin"));
  margin.click();
  assert.equal(doc.querySelector('#headToHeadContent th[aria-sort="descending"]').textContent.trim().startsWith("Margin"), true);
  const first = doc.querySelector(".rivalry-table tbody tr").textContent;
  ui.prepareSeason("2018", true, null);
  ui.renderRivalry(pair);
  assert.equal(doc.querySelector(".rivalry-table tbody tr").textContent, first);
  assert.equal(doc.getElementById("h2hOwnerA").value, "gaurav");
  ui.renderRivalry(null);
  assert.match(doc.getElementById("headToHeadStatus").textContent, /retained/);
});

test("research deep links and late era/pair responses survive outage, season changes and back navigation", async (t) => {
  const doc = environment(t, "http://localhost/?tab=head-to-head&h2hEra=all&ownerA=gaurav&ownerB=alex");
  const previousFetch = globalThis.fetch;
  t.after(() => { globalThis.fetch = previousFetch; });
  const delayed = [];
  let deferResearch = false;
  const response = (data, ok = true) => ({ ok, json: async () => data });
  globalThis.fetch = async (url) => {
    const parsed = new URL(url, location.href);
    if (parsed.pathname === "/api/seasons") return response(catalog);
    if (parsed.pathname === "/api/owners") return response(archive.careers(null, { currentSeason: "2026" }));
    if (parsed.pathname === "/api/dashboard" || parsed.pathname === "/api/refresh") {
      const year = parsed.searchParams.get("season");
      return year && year !== "2026" ? response(archive.dashboard(year)) : response({ error: "Sleeper unavailable" }, false);
    }
    const era = parsed.searchParams.get("era");
    const data = parsed.pathname === "/api/records" ? leagueRecords(archive.archive, null, { era }) : headToHead(archive.archive, null, { era, stage: parsed.searchParams.get("stage") || "all", ownerA: parsed.searchParams.get("ownerA") || undefined, ownerB: parsed.searchParams.get("ownerB") || undefined });
    if (deferResearch) return new Promise((resolve) => delayed.push(() => resolve(response(data))));
    return response(data);
  };
  const source = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll('"./live.js"', JSON.stringify(new URL("../src/live.js", import.meta.url).href)).replaceAll('"./live-state.js"', JSON.stringify(new URL("../src/live-state.js", import.meta.url).href)).replace('"./ui.js"', JSON.stringify(`${new URL("../src/ui.js", import.meta.url).href}?researchApp=${Date.now()}`));
  await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
  await flush();
  assert.equal(doc.getElementById("headToHeadTab").getAttribute("aria-selected"), "true");
  assert.equal(doc.getElementById("h2hOwnerA").value, "gaurav");
  assert.match(doc.getElementById("headToHeadContent").textContent, /Alex Henoch/);
  assert.match(doc.getElementById("headToHeadStatus").textContent, /Current-season results unavailable/);
  deferResearch = true;
  const era = doc.getElementById("h2hEra");
  era.value = "ten-team"; era.dispatchEvent(new window.Event("change"));
  assert.equal(doc.getElementById("headToHeadContent").textContent, "");
  const owner = doc.getElementById("h2hOwnerB");
  owner.value = "jake"; owner.dispatchEvent(new window.Event("change"));
  delayed.pop()(); await flush();
  assert.match(doc.getElementById("headToHeadContent").textContent, /Jake Herman/);
  assert.match(location.search, /ownerB=jake/);
  delayed.pop()(); await flush();
  assert.doesNotMatch(doc.getElementById("headToHeadContent").textContent, /Alex Henoch/);
  assert.equal(doc.getElementById("h2hEra").value, "ten-team");
  deferResearch = false;
  const select = doc.getElementById("seasonSelect");
  select.value = "2025"; select.dispatchEvent(new window.Event("change")); await flush();
  assert.equal(doc.getElementById("headToHeadTab").getAttribute("aria-selected"), "true");
  assert.equal(doc.getElementById("h2hOwnerB").value, "jake");
  doc.getElementById("recordsTab").click(); await flush();
  assert.equal(doc.getElementById("recordsEra").value, "ten-team");
  assert.match(location.search, /tab=records/);
  deferResearch = true;
  const recordsEra = doc.getElementById("recordsEra");
  recordsEra.value = "all"; recordsEra.dispatchEvent(new window.Event("change"));
  recordsEra.value = "ten-team"; recordsEra.dispatchEvent(new window.Event("change"));
  delayed.pop()(); delayed.pop()(); await flush();
  assert.match(doc.getElementById("recordsStatus").textContent, /10-team era/);
  assert.doesNotMatch(doc.getElementById("recordsStatus").textContent, /2018/);
  deferResearch = false;
  history.pushState(null, "", "?season=2025&owner=gaurav&tab=head-to-head&h2hEra=all&ownerA=gaurav&ownerB=alex");
  window.dispatchEvent(new window.PopStateEvent("popstate")); await flush();
  assert.equal(doc.getElementById("headToHeadTab").getAttribute("aria-selected"), "true");
  assert.equal(doc.getElementById("h2hEra").value, "all");
  assert.equal(doc.getElementById("h2hOwnerB").value, "alex");
  deferResearch = true;
  const stageButton = (stage) => doc.querySelector(`#h2hStageControls [data-stage="${stage}"]`);
  stageButton("regular").click();
  stageButton("playoff").click();
  assert.equal(doc.getElementById("headToHeadContent").textContent, "");
  delayed.pop()(); await flush();
  assert.equal(stageButton("playoff").getAttribute("aria-pressed"), "true");
  assert.match(doc.querySelector(".rivalry-scope").textContent, /^Playoffs/);
  const playoffCount = doc.querySelectorAll(".rivalry-table tbody tr").length;
  assert.ok(playoffCount > 0);
  assert.ok([...doc.querySelectorAll(".rivalry-table tbody tr")].every((row) => row.children[2].textContent === "Playoffs"));
  assert.match(location.search, /h2hStage=playoff/);
  delayed.pop()(); await flush();
  assert.equal(doc.querySelectorAll(".rivalry-table tbody tr").length, playoffCount);
  assert.match(doc.querySelector(".rivalry-scope").textContent, /^Playoffs/);
  deferResearch = false;
  stageButton("regular").click(); await flush();
  assert.match(doc.querySelector(".rivalry-scope").textContent, /^Regular season/);
  assert.ok([...doc.querySelectorAll(".rivalry-table tbody tr")].every((row) => row.children[2].textContent === "Regular season"));
  history.pushState(null, "", "?season=2025&tab=head-to-head&h2hEra=all&h2hStage=playoff&ownerA=gaurav&ownerB=alex");
  window.dispatchEvent(new window.PopStateEvent("popstate")); await flush();
  assert.equal(stageButton("playoff").getAttribute("aria-pressed"), "true");
  assert.equal(doc.querySelectorAll(".rivalry-table tbody tr").length, playoffCount);
  doc.querySelector("#headToHeadContent tbody a").click(); await flush();
  assert.equal(doc.getElementById("overviewTab").getAttribute("aria-selected"), "true");
  assert.match(doc.querySelector(".owner-highlight").textContent, /Gaurav/);
});

function environment(t, url = "http://localhost/") {
  const dom = new JSDOM(html, { url });
  for (const key of ["window", "document", "Node", "location", "history"]) {
    const old = Object.getOwnPropertyDescriptor(globalThis, key);
    Object.defineProperty(globalThis, key, { value: dom.window[key], configurable: true, writable: true });
    t.after(() => { if (old) Object.defineProperty(globalThis, key, old); else delete globalThis[key]; });
  }
  dom.window.HTMLElement.prototype.scrollIntoView = function () {};
  t.after(() => dom.window.close());
  return dom.window.document;
}

test("a successful live-only refresh clears connection warnings without replacing other views", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?liveRecovery=${Date.now()}`);
  const payload = archive.dashboard("2025");
  ui.renderDashboard(payload.stats, payload);
  const matrix = doc.getElementById("matrixTable").firstChild;
  ui.renderConnectionWarning();
  assert.match(doc.getElementById("noticeRegion").textContent, /Connection interrupted/);
  ui.renderLiveWeek(payload.stats, { warnings: [], cachedAt: new Date().toISOString() });
  assert.equal(doc.getElementById("noticeRegion").textContent, "");
  assert.equal(doc.getElementById("matrixTable").firstChild, matrix);
});

test("season UI: archive recap, owner profiles, links, visible-tab keyboard navigation and preferences", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?test=${Date.now()}`);
  const selections = [];
  ui.initializeUi({ onRefresh() {}, onSeasonChange: (...args) => selections.push(args) });
  ui.renderSeasons(catalog, "2025");
  doc.getElementById("liveTab").click();
  ui.prepareSeason("2025", true, null);
  const payload = archive.dashboard("2025");
  ui.renderDashboard(payload.stats, payload);
  assert.equal(doc.getElementById("overviewTab").getAttribute("aria-selected"), "true");
  assert.equal(doc.getElementById("liveTab").hidden, true);
  assert.equal(doc.getElementById("draftTab").hidden, true);
  assert.equal(doc.getElementById("refreshButton").hidden, true);
  assert.equal(doc.getElementById("statusTitle").textContent, "ESPN archive");
  assert.match(doc.getElementById("seasonRange").textContent, /14.*10 teams/);
  assert.equal(doc.querySelectorAll("#matrixTable tbody tr").length, 10);
  payload.stats.teams[0].canonicalOwnerIds = ["gaurav"];
  payload.stats.teams[0].avatarUrl = "https://example.com/sleeper-avatar.png";
  ui.renderDashboard(payload.stats, payload);
  assert.equal(doc.querySelector("#matrixTable .team-avatar img")?.getAttribute("src"), "./img/avatars/gaurav.png");
  assert.equal(doc.querySelector("#matrixTable .team-copy > strong .team-record-inline"), null);
  assert.match(doc.querySelector("#matrixTable .team-copy > span .team-record-inline")?.textContent, /^\(\d+-\d+/);
  assert.match(doc.getElementById("seasonRecap").textContent, /Champion/);
  doc.getElementById("overviewTab").dispatchEvent(new window.KeyboardEvent("keydown", { key: "ArrowRight", bubbles: true }));
  assert.equal(doc.activeElement.id, "weeklyTab");
  doc.getElementById("weeklyTab").dispatchEvent(new window.KeyboardEvent("keydown", { key: "End", bubbles: true }));
  assert.equal(doc.activeElement.id, "headToHeadTab");
  const mode = [...doc.querySelectorAll("#matrixControls button")].find((button) => button.textContent.includes("Rank"));
  mode.click();
  assert.equal(doc.querySelectorAll("#trendControls input").length, 10);
  assert.equal(doc.querySelectorAll("#trendControls .owner-icon").length, 10);
  assert.ok([...doc.querySelectorAll("#trendControls .owner-icon")].every((img) => img.alt));
  assert.equal(doc.querySelectorAll("#trendChart .chart-line").length, 10);
  assert.ok(doc.querySelector("#trendChart .owner-trend-avatar"));
  const originalLine = doc.querySelector('#trendChart [data-owner="gaurav"]');
  const originalStyle = [originalLine.getAttribute("stroke"), originalLine.getAttribute("stroke-dasharray")];
  const trendGaurav = [...doc.querySelectorAll("#trendControls label")].find((label) => label.title === "Gaurav Gandhi");
  trendGaurav.querySelector("input").checked = false;
  trendGaurav.querySelector("input").dispatchEvent(new window.Event("change"));
  assert.equal(doc.querySelector('#trendChart [data-owner="gaurav"]'), null);
  trendGaurav.querySelector("input").checked = true;
  trendGaurav.querySelector("input").dispatchEvent(new window.Event("change"));
  assert.ok(doc.querySelector('#trendChart [data-owner="gaurav"]'));
  const past = archive.dashboard("2018");
  ui.prepareSeason("2018", true, "gaurav");
  ui.renderDashboard(past.stats, past);
  assert.match(doc.getElementById("seasonRange").textContent, /13.*12 teams/);
  assert.equal(doc.querySelectorAll("#matrixTable tbody tr").length, 12);
  assert.match(doc.querySelector("#matrixTable .owner-highlight").textContent, /Gaurav/);
  assert.match(doc.querySelector("#matrixTable caption").textContent, /rank/);
  assert.equal(doc.querySelectorAll("#trendChart .chart-line").length, 12);
  assert.equal(doc.querySelectorAll("#trendControls .trend-owner-key").length, 12);
  const oldLine = doc.querySelector('#trendChart [data-owner="gaurav"]');
  assert.deepEqual([oldLine.getAttribute("stroke"), oldLine.getAttribute("stroke-dasharray")], originalStyle);
  ui.renderOwners(archive.careers(null, { currentSeason: "2026" }));
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 10);
  const filter = doc.getElementById("currentOwnersOnly");
  filter.checked = false;
  filter.dispatchEvent(new window.Event("change"));
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 14);
  assert.equal(doc.querySelectorAll("#ownersContent tbody .owner-icon").length, 10);
  const ownerRow = (name) => [...doc.querySelectorAll("#ownersContent tbody tr")].find((row) => row.textContent.startsWith(name));
  assert.match(ownerRow("Ben Dross").querySelector("img").src, /dross\.png$/);
  assert.match(ownerRow("Ethan Miller").querySelector("img").src, /ethan_miller\.png$/);
  assert.equal(ownerRow("Daniel Pyo / Ethan Miller").querySelector("img"), null);
  assert.equal([...doc.querySelectorAll("#ownersContent thead th")].some((cell) => cell.textContent.includes("Titles")), false);
  filter.checked = true;
  filter.dispatchEvent(new window.Event("change"));
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 10);
  const gaurav = [...doc.querySelectorAll(".owner-button")].find((button) => button.textContent.includes("Gaurav"));
  assert.match(gaurav.textContent, /🏆/);
  gaurav.click();
  assert.match(doc.querySelector("#ownersContent h3").textContent, /^Gaurav Gandhi/);
  assert.match(doc.querySelector("#ownersContent h3").textContent, /🏆/);
  const link = doc.querySelector("#ownersContent a");
  assert.match(link.href, /season=2025&owner=gaurav/);
  link.click();
  assert.deepEqual(selections.at(-1), ["2025", "gaurav"]);
  ui.prepareSeason("2026", false, null);
  assert.equal(doc.getElementById("draftTab").hidden, false);
  assert.equal(doc.getElementById("refreshButton").hidden, false);
});

test("client ignores late season/refresh responses and handles deep links and back navigation", async (t) => {
  const doc = environment(t);
  let resolveOldSeason;
  let resolveRefresh;
  const oldFetch = globalThis.fetch;
  t.after(() => { globalThis.fetch = oldFetch; });
  const current = archive.dashboard("2025");
  current.source = "sleeper";
  current.stats.metadata.season = "2026";
  current.recap = null;
  const response = (body) => ({ ok: true, json: async () => body });
  globalThis.fetch = async (url) => {
    if (url === "/api/seasons") return response(catalog);
    if (url === "/api/owners") return response(archive.careers(null, { currentSeason: "2026" }));
    if (url === "/api/refresh") return new Promise((resolve) => { resolveRefresh = () => resolve(response(current)); });
    if (url.endsWith("season=2018")) return new Promise((resolve) => { resolveOldSeason = () => resolve(response(archive.dashboard("2018"))); });
    if (url.endsWith("season=2025")) return response(archive.dashboard("2025"));
    return response(current);
  };
  const source = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll('"./live.js"', JSON.stringify(new URL("../src/live.js", import.meta.url).href)).replaceAll('"./live-state.js"', JSON.stringify(new URL("../src/live-state.js", import.meta.url).href)).replace('"./ui.js"', JSON.stringify(`${new URL("../src/ui.js", import.meta.url).href}?race=${Date.now()}`));
  await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
  assert.match(doc.getElementById("brandSeason").textContent, /2026/);
  const select = doc.getElementById("seasonSelect");
  select.value = "2018";
  select.dispatchEvent(new window.Event("change"));
  select.value = "2025";
  select.dispatchEvent(new window.Event("change"));
  await flush();
  assert.match(doc.getElementById("brandSeason").textContent, /2025/);
  resolveOldSeason(); resolveRefresh(); await flush();
  assert.match(doc.getElementById("brandSeason").textContent, /2025/);
  assert.equal(doc.querySelectorAll("#matrixTable tbody tr").length, 10);
  assert.equal(doc.getElementById("refreshButton").hidden, true);
  history.pushState(null, "", "?season=2018&owner=gaurav");
  window.dispatchEvent(new window.PopStateEvent("popstate"));
  resolveOldSeason(); await flush();
  assert.match(doc.getElementById("brandSeason").textContent, /2018/);
  assert.match(doc.querySelector(".owner-highlight").textContent, /Gaurav/);
  assert.equal(doc.getElementById("seasonSelect").value, "2018");
});

test("initial archive deep link loads highlighted owner without refreshing Sleeper", async (t) => {
  const doc = environment(t, "http://localhost/?season=2022&owner=gaurav");
  const oldFetch = globalThis.fetch;
  t.after(() => { globalThis.fetch = oldFetch; });
  const calls = [];
  globalThis.fetch = async (url) => {
    calls.push(url);
    const payload = url === "/api/seasons" ? catalog : url === "/api/owners" ? archive.careers(null, { currentSeason: "2026" }) : archive.dashboard("2022");
    return { ok: true, json: async () => payload };
  };
  const source = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll('"./live.js"', JSON.stringify(new URL("../src/live.js", import.meta.url).href)).replaceAll('"./live-state.js"', JSON.stringify(new URL("../src/live-state.js", import.meta.url).href)).replace('"./ui.js"', JSON.stringify(`${new URL("../src/ui.js", import.meta.url).href}?deep=${Date.now()}`));
  await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
  await flush();
  assert.equal(calls.includes("/api/refresh"), false);
  assert.equal(doc.getElementById("seasonSelect").value, "2022");
  assert.match(doc.querySelector(".owner-highlight").textContent, /Gaurav/);
  assert.doesNotMatch(doc.getElementById("seasonRecap").textContent, /Manual True League title correction/);
  assert.match(doc.getElementById("seasonRecap").textContent, /Champion · Gaurav Gandhi/);
  assert.match(doc.getElementById("ownersStatus").textContent, /Current-season contributions are unavailable/);
});

test("trend sums weekly score-minus-median with full precision and excludes provisional weeks", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?cumulative=${Date.now()}`);
  ui.initializeUi({ onRefresh() {} });
  const payload = archive.dashboard("2025");
  payload.stats.weeks = payload.stats.weeks.slice(0, 2);
  const team = payload.stats.teams[0];
  payload.stats.weeks[0].entries.find((entry) => entry.rosterId === team.rosterId).score = 12.34;
  payload.stats.weeks[1].entries.find((entry) => entry.rosterId === team.rosterId).score = 23.45;
  payload.stats.weeks[0].leagueMedian = 10;
  payload.stats.weeks[1].leagueMedian = 30;
  payload.stats.liveWeek = { ...structuredClone(payload.stats.weeks[1]), week: 3, status: "live" };
  ui.renderDashboard(payload.stats, payload);
  const titles = [...doc.querySelectorAll("#trendChart .chart-dot title")].map((node) => node.textContent);
  assert.ok(titles.includes(`${team.managerName.split(/\s+/)[0]}, through Week 1: +2.34 cumulative vs median`));
  assert.ok(titles.includes(`${team.managerName.split(/\s+/)[0]}, through Week 2: -4.21 cumulative vs median`));
  assert.ok(titles.every((title) => !title.includes("Week 3")));
  assert.ok(doc.querySelector("#trendChart .chart-median"));
  payload.stats.weeks = payload.stats.weeks.slice(0, 1);
  ui.renderDashboard(payload.stats, payload);
  assert.ok(!doc.querySelector("#trendChart svg").outerHTML.includes("NaN"));
  payload.stats.weeks = [];
  ui.renderDashboard(payload.stats, payload);
  assert.match(doc.getElementById("trendChart").textContent, /No finalized trends yet/);
});

test("live matrix cells have no heat or median marker and do not rescale finalized cells", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?matrix=${Date.now()}`);
  ui.initializeUi({ onRefresh() {} });
  const payload = archive.dashboard("2025");
  payload.stats.weeks = payload.stats.weeks.slice(0, 1);
  ui.renderDashboard(payload.stats, payload);
  const shades = [...doc.querySelectorAll("#matrixTable .matrix-scored")].map((cell) => cell.getAttribute("style"));
  const totals = [...doc.querySelectorAll("#matrixTable tbody tr")].map((row) => row.lastElementChild.textContent);
  assert.equal(doc.querySelector("#matrixTable thead tr").lastElementChild.textContent, "Total PF");
  assert.deepEqual(totals, payload.stats.teams.map((team) => team.total.toFixed(2)));
  assert.ok(doc.querySelector("#matrixTable .matrix-result-win"));
  assert.ok(doc.querySelector("#matrixTable .matrix-result-loss"));
  payload.stats.liveWeek = { ...structuredClone(payload.stats.weeks[0]), week: 2, status: "live" };
  payload.stats.liveWeek.entries.forEach((entry) => { entry.score = 99999; });
  ui.renderDashboard(payload.stats, payload);
  assert.deepEqual([...doc.querySelectorAll("#matrixTable .matrix-scored")].map((cell) => cell.getAttribute("style")), shades);
  assert.equal(doc.querySelectorAll("#matrixTable .matrix-live-cell.matrix-scored, #matrixTable .matrix-live-cell .matrix-median-marker, #matrixTable .matrix-live-cell .matrix-result-marker").length, 0);
  assert.match(doc.querySelector(".matrix-live-head").textContent, /Live/);
  assert.ok(doc.querySelectorAll("#statbookTable .career-colored").length > 0);
  assert.equal(doc.querySelector("#statbookTable tbody tr").firstElementChild.classList.contains("career-colored"), false);
  assert.equal(doc.querySelector("#statbookTable .record-pill").parentElement.classList.contains("career-colored"), false);
  assert.ok([...doc.querySelectorAll("#statbookTable thead button")].some((button) => button.textContent === "Good/Avg/Bad"));
  assert.ok([...doc.querySelectorAll("#statbookTable thead button")].some((button) => button.textContent === "Lucky/Unlucky"));
  assert.equal([...doc.querySelectorAll("#statbookTable thead .group-head")].some((head) => head.textContent === "Records"), true);
  assert.ok([...doc.querySelectorAll("#statbookTable tbody tr:first-child .record-pill")].some((pill) => /^\d+-\d+/.test(pill.textContent)));
  assert.ok([...doc.querySelectorAll("#statbookTable tbody tr:first-child td")].some((cell) => /^\d+ \/ \d+ \/ \d+$/.test(cell.textContent)));
  assert.ok([...doc.querySelectorAll("#statbookTable tbody td")].some((cell) => /^\d+\.\d$/.test(cell.textContent)));
  assert.ok([...doc.querySelectorAll("#statbookTable tbody td")].some((cell) => /^\d+\.\d{2}$/.test(cell.textContent)));
  assert.equal(doc.getElementById("statbookTable").compareDocumentPosition(doc.getElementById("leagueBenchmarks")) & Node.DOCUMENT_POSITION_FOLLOWING, Node.DOCUMENT_POSITION_FOLLOWING);
  assert.doesNotMatch(doc.getElementById("leagueBenchmarks").textContent, /Median pts > median|Finalized scores/);
  assert.match(doc.getElementById("leagueBenchmarks").textContent, /Season high/);
  assert.match(doc.getElementById("leagueBenchmarks").textContent, /Season low/);
  for (const button of doc.querySelectorAll("#matrixControls button")) {
    button.click();
    assert.deepEqual([...doc.querySelectorAll("#matrixTable tbody tr")].map((row) => row.lastElementChild.textContent), totals);
    const count = doc.querySelector("#matrixTable thead tr").children.length;
    assert.ok([...doc.querySelectorAll("#matrixTable tbody tr, #matrixTable tfoot tr")].every((row) => row.children.length === count));
  }
  assert.doesNotMatch(doc.body.textContent, /Red to green =|Regular-season results across all seasons/);
});

test("owner sorting, era profiles, conditional colors and matching-cache fallback", async (t) => {
  const doc = environment(t);
  const ui = await import(`../src/ui.js?owners=${Date.now()}`);
  ui.initializeUi({ onRefresh() {} });
  const all = archive.careers(null);
  const ten = archive.careers(null, { era: "ten-team" });
  doc.getElementById("currentOwnersOnly").checked = false;
  ui.renderOwners(all);
  const header = (label) => [...doc.querySelectorAll("#ownersContent thead button")].find((button) => button.textContent.replace(/[↑↓]/g, "").trim() === label);
  assert.ok(header("Lucky/Unlucky"));
  header("PF").click();
  assert.match(doc.querySelector("#ownersContent .owner-button").textContent, new RegExp([...all.owners].sort((a, b) => b.pointsFor - a.pointsFor)[0].name));
  assert.equal(doc.activeElement, header("PF"));
  assert.equal(doc.querySelectorAll('#ownersContent th[aria-sort="descending"]').length, 1);
  assert.equal(doc.querySelector("#ownersContent tbody th").classList.contains("career-colored"), false);
  assert.ok(doc.querySelectorAll("#ownersContent .career-colored").length > 0);
  assert.doesNotMatch(doc.getElementById("ownersContent").textContent, /Former/);
  assert.ok([...doc.querySelectorAll(".owner-button")].some((button) => button.textContent.includes("Daniel Pyo / Ethan Miller") && button.textContent.includes("🪦")));
  assert.ok(doc.querySelector("#ownersContent .owner-trend-chart"));
  assert.ok(doc.querySelector("#ownersContent .owner-trend-avatar"));
  assert.ok(doc.querySelector("#ownersContent .owner-trend-grave"));
  assert.ok(doc.querySelectorAll("#ownersContent .owner-trend-filter input").length > 0);
  const ownerTrendGaurav = [...doc.querySelectorAll("#ownersContent .owner-trend-filter label")].find((label) => label.title === "Gaurav Gandhi");
  ownerTrendGaurav.querySelector("input").checked = false;
  ownerTrendGaurav.querySelector("input").dispatchEvent(new window.Event("change"));
  assert.equal(doc.querySelector('#ownersContent .owner-trend-chart [data-owner="gaurav"]'), null);
  ownerTrendGaurav.querySelector("input").checked = true;
  ownerTrendGaurav.querySelector("input").dispatchEvent(new window.Event("change"));
  assert.ok(doc.querySelector('#ownersContent .owner-trend-chart [data-owner="gaurav"]'));
  const kyle = [...doc.querySelectorAll(".owner-button")].find((button) => button.textContent.includes("Kyle"));
  kyle.click();
  ui.prepareOwnerEra("ten-team");
  assert.doesNotMatch(doc.getElementById("ownersContent").textContent, /Kyle/);
  ui.renderOwners(ten);
  assert.match(doc.getElementById("ownersContent").textContent, /No seasons in this era/);
  ui.prepareOwnerEra("all");
  ui.renderOwners(all);
  assert.match(doc.querySelector("#ownersContent h3").textContent, /Kyle/);
  assert.ok(doc.querySelector(".career-performance"));
  header("Season").click();
  const seasonLink = () => doc.querySelector("#ownersContent a").textContent;
  assert.equal(seasonLink(), "2018");
  ui.renderOwners(all);
  assert.equal(seasonLink(), "2018");
  doc.getElementById("currentOwnersOnly").checked = true;
  doc.getElementById("currentOwnersOnly").dispatchEvent(new window.Event("change"));
  assert.match(doc.querySelector("#ownersContent h3").textContent, /Kyle/);
  ui.prepareOwnerEra("ten-team");
  ui.renderOwners(null);
  assert.match(doc.getElementById("ownersStatus").textContent, /previous data for this era retained/);
  assert.match(doc.getElementById("ownersContent").textContent, /No seasons in this era/);
  doc.querySelector("#ownersContent .refresh-button").click();
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 10);
  assert.ok([...doc.querySelectorAll("#ownersContent tbody tr")].every((row) => !row.textContent.includes("Kyle")));
  assert.equal(doc.querySelector("#ownersContent .owner-trend-grave"), null);
  const neutral = structuredClone(ten);
  neutral.owners.forEach((owner) => { owner.pointsFor = 100; owner.winPct = 0.5; owner.averageDeltaMedian = 0; });
  ui.renderOwners(neutral);
  const first = doc.querySelector("#ownersContent tbody tr");
  for (const index of [3, 5, 10]) assert.equal(first.children[index].style.getPropertyValue("--score-shade"), "0.00%");
});

test("era switching ignores late responses and never presents all-era totals as ten-team", async (t) => {
  const doc = environment(t, "http://localhost/?season=2025");
  const oldFetch = globalThis.fetch;
  t.after(() => { globalThis.fetch = oldFetch; });
  let resolveTen;
  let failTen = false;
  const response = (body) => ({ ok: true, json: async () => body });
  globalThis.fetch = async (url) => {
    if (url === "/api/seasons") return response(catalog);
    if (url === "/api/owners") return response(archive.careers(null));
    if (url === "/api/owners?era=ten-team") {
      if (failTen) throw new Error("offline");
      return new Promise((resolve) => { resolveTen = () => resolve(response(archive.careers(null, { era: "ten-team" }))); });
    }
    return response(archive.dashboard("2025"));
  };
  const source = (await readFile(new URL("../src/app.js", import.meta.url), "utf8")).replaceAll('"./live.js"', JSON.stringify(new URL("../src/live.js", import.meta.url).href)).replaceAll('"./live-state.js"', JSON.stringify(new URL("../src/live-state.js", import.meta.url).href)).replace('"./ui.js"', JSON.stringify(`${new URL("../src/ui.js", import.meta.url).href}?eraRace=${Date.now()}`));
  await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
  await flush();
  const change = (value) => { doc.getElementById("ownerEra").value = value; doc.getElementById("ownerEra").dispatchEvent(new window.Event("change")); };
  change("ten-team");
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 0);
  change("all"); await flush();
  resolveTen(); await flush();
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 10);
  assert.equal(doc.getElementById("ownerEra").value, "all");
  failTen = true;
  change("ten-team"); await flush();
  assert.equal(doc.querySelectorAll("#ownersContent tbody tr").length, 0);
  assert.match(doc.getElementById("ownersContent").textContent, /unavailable/);
});
